### ISSUE TITLE
open/R build fails while running build_openr.sh

### ISSUE THREAD

**Issue by P3RP** [facebook/openr#38]
*Please use this template for reporting suspected bugs or requests for help.*

# Issue Description
Open/R build fails while running build_openr.sh. 

# Environment
OS version: ubuntu-16.04

# Minimal test code / Steps to reproduce the issue
openr-master/build$ sudo bash ./build_openr.sh

# What's the actual result?
[ 85%] Linking CXX executable openr
/usr/bin/ld: /usr/local/lib/libfbzmq.a(ResourceMonitor.cpp.o): undefined reference to symbol '_ZN5boost10filesystem6detail6statusERKNS0_4pathEPNS_6system10error_codeE'
//usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.58.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
CMakeFiles/openr.dir/build.make:132: recipe for target 'openr' failed
make[2]: *** [openr] Error 1
CMakeFiles/Makefile2:1385: recipe for target 'CMakeFiles/openr.dir/all' failed
make[1]: *** [CMakeFiles/openr.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

# What's the expected result?
OpenR built and installed successfully

**Comment by butjar** [comment]
Same problem here. `build_openr.sh` doesn't build on Ubuntu 16.04. Do you use the docker build instead? This works well for me, I realized that the versions of the dependencies differ from the build script.

If you do not maintain the build script, could you explain how to extract the build artifacts from docker and install them ?

**Comment by saifhhasan** [comment]
Hello @butjar - `build_openr.sh` can be used to  build but you will need to fix minor errors. Folks in past have done that.

Build openr in non-shared mode (You will have to modify openr build step in generated docker file). Copy openr binary (`/usr/sbin/openr`) and python modules (/usr/lib/<py-version>/site-packages). It should work.
